
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.story
{
public sealed partial class dialog_illustration_map : Luban.BeanBase
{
    public dialog_illustration_map(JSONNode _buf) 
    {
        { if(!_buf["nameCn"].IsString) { throw new SerializationException(); }  NameCn = _buf["nameCn"]; }
        { if(!_buf["nameEn"].IsString) { throw new SerializationException(); }  NameEn = _buf["nameEn"]; }
        { if(!_buf["directory"].IsString) { throw new SerializationException(); }  Directory = _buf["directory"]; }
        { if(!_buf["nameColor"].IsString) { throw new SerializationException(); }  NameColor = _buf["nameColor"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["typeNonc"].IsString) { throw new SerializationException(); }  TypeNonc = _buf["typeNonc"]; }
        { if(!_buf["typeDulp"].IsString) { throw new SerializationException(); }  TypeDulp = _buf["typeDulp"]; }
        { if(!_buf["typeInvs"].IsString) { throw new SerializationException(); }  TypeInvs = _buf["typeInvs"]; }
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
    }

    public static dialog_illustration_map Deserializedialog_illustration_map(JSONNode _buf)
    {
        return new story.dialog_illustration_map(_buf);
    }

    /// <summary>
    /// 中文名（需要和对话里的名字对应）
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 英文名
    /// </summary>
    public readonly string NameEn;
    /// <summary>
    /// 文件目录（Resources下）
    /// </summary>
    public readonly string Directory;
    /// <summary>
    /// 名字颜色
    /// </summary>
    public readonly string NameColor;
    /// <summary>
    /// 简介
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 非角色
    /// </summary>
    public readonly string TypeNonc;
    /// <summary>
    /// 重复命名
    /// </summary>
    public readonly string TypeDulp;
    /// <summary>
    /// 不显示
    /// </summary>
    public readonly string TypeInvs;
    public readonly int Id;
   
    public const int __ID__ = 448333323;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nameCn:" + NameCn + ","
        + "nameEn:" + NameEn + ","
        + "directory:" + Directory + ","
        + "nameColor:" + NameColor + ","
        + "description:" + Description + ","
        + "typeNonc:" + TypeNonc + ","
        + "typeDulp:" + TypeDulp + ","
        + "typeInvs:" + TypeInvs + ","
        + "id:" + Id + ","
        + "}";
    }
}

}

