
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.story
{
public sealed partial class dialog : Luban.BeanBase
{
    public dialog(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["nameCn"].IsString) { throw new SerializationException(); }  NameCn = _buf["nameCn"]; }
        { if(!_buf["illustration"].IsString) { throw new SerializationException(); }  Illustration = _buf["illustration"]; }
        { if(!_buf["textCn"].IsString) { throw new SerializationException(); }  TextCn = _buf["textCn"]; }
        { if(!_buf["direction"].IsString) { throw new SerializationException(); }  Direction = _buf["direction"]; }
    }

    public static dialog Deserializedialog(JSONNode _buf)
    {
        return new story.dialog(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文名（不填默认为旁白）
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 立绘差分（不填默认为Default）
    /// </summary>
    public readonly string Illustration;
    /// <summary>
    /// 中文文本
    /// </summary>
    public readonly string TextCn;
    /// <summary>
    /// 对话框位置（默认左）
    /// </summary>
    public readonly string Direction;
   
    public const int __ID__ = 707173473;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameCn:" + NameCn + ","
        + "illustration:" + Illustration + ","
        + "textCn:" + TextCn + ","
        + "direction:" + Direction + ","
        + "}";
    }
}

}

