
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.story
{
public sealed partial class dialog_branch_map : Luban.BeanBase
{
    public dialog_branch_map(JSONNode _buf) 
    {
        { if(!_buf["branchName"].IsString) { throw new SerializationException(); }  BranchName = _buf["branchName"]; }
        { if(!_buf["startRow"].IsNumber) { throw new SerializationException(); }  StartRow = _buf["startRow"]; }
        { if(!_buf["note"].IsString) { throw new SerializationException(); }  Note = _buf["note"]; }
    }

    public static dialog_branch_map Deserializedialog_branch_map(JSONNode _buf)
    {
        return new story.dialog_branch_map(_buf);
    }

    /// <summary>
    /// 分支段落名（不可重复）
    /// </summary>
    public readonly string BranchName;
    /// <summary>
    /// 起始行
    /// </summary>
    public readonly int StartRow;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Note;
   
    public const int __ID__ = -558220323;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "branchName:" + BranchName + ","
        + "startRow:" + StartRow + ","
        + "note:" + Note + ","
        + "}";
    }
}

}

