
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.story
{
public sealed partial class dialog_chapter_map : Luban.BeanBase
{
    public dialog_chapter_map(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["dialogName"].IsString) { throw new SerializationException(); }  DialogName = _buf["dialogName"]; }
        { if(!_buf["startRow"].IsNumber) { throw new SerializationException(); }  StartRow = _buf["startRow"]; }
        { if(!_buf["chapterName"].IsString) { throw new SerializationException(); }  ChapterName = _buf["chapterName"]; }
        { if(!_buf["chapter"].IsString) { throw new SerializationException(); }  Chapter = _buf["chapter"]; }
    }

    public static dialog_chapter_map Deserializedialog_chapter_map(JSONNode _buf)
    {
        return new story.dialog_chapter_map(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 段落名
    /// </summary>
    public readonly string DialogName;
    /// <summary>
    /// 起始行
    /// </summary>
    public readonly int StartRow;
    /// <summary>
    /// 章节
    /// </summary>
    public readonly string ChapterName;
    /// <summary>
    /// 所属篇目
    /// </summary>
    public readonly string Chapter;
   
    public const int __ID__ = 1367790476;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "dialogName:" + DialogName + ","
        + "startRow:" + StartRow + ","
        + "chapterName:" + ChapterName + ","
        + "chapter:" + Chapter + ","
        + "}";
    }
}

}

