
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.story
{
public sealed partial class npc_basic_info : Luban.BeanBase
{
    public npc_basic_info(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["power"].IsNumber) { throw new SerializationException(); }  Power = _buf["power"]; }
        { if(!_buf["influence"].IsNumber) { throw new SerializationException(); }  Influence = _buf["influence"]; }
        { if(!_buf["interest"].IsString) { throw new SerializationException(); }  Interest = _buf["interest"]; }
        { if(!_buf["grouptag"].IsString) { throw new SerializationException(); }  Grouptag = _buf["grouptag"]; }
        { if(!_buf["dialog"].IsString) { throw new SerializationException(); }  Dialog = _buf["dialog"]; }
        { if(!_buf["texture"].IsString) { throw new SerializationException(); }  Texture = _buf["texture"]; }
        { if(!_buf["hour3"].IsString) { throw new SerializationException(); }  Hour3 = _buf["hour3"]; }
        { if(!_buf["hour6"].IsString) { throw new SerializationException(); }  Hour6 = _buf["hour6"]; }
        { if(!_buf["hour9"].IsString) { throw new SerializationException(); }  Hour9 = _buf["hour9"]; }
        { if(!_buf["hour12"].IsString) { throw new SerializationException(); }  Hour12 = _buf["hour12"]; }
        { if(!_buf["hour15"].IsString) { throw new SerializationException(); }  Hour15 = _buf["hour15"]; }
        { if(!_buf["hour18"].IsString) { throw new SerializationException(); }  Hour18 = _buf["hour18"]; }
        { if(!_buf["hour21"].IsString) { throw new SerializationException(); }  Hour21 = _buf["hour21"]; }
        { if(!_buf["hour0"].IsString) { throw new SerializationException(); }  Hour0 = _buf["hour0"]; }
    }

    public static npc_basic_info Deserializenpc_basic_info(JSONNode _buf)
    {
        return new story.npc_basic_info(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 人物名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 权势
    /// </summary>
    public readonly int Power;
    /// <summary>
    /// 影响力
    /// </summary>
    public readonly int Influence;
    /// <summary>
    /// 话题
    /// </summary>
    public readonly string Interest;
    /// <summary>
    /// tag
    /// </summary>
    public readonly string Grouptag;
    /// <summary>
    /// 对话表目录
    /// </summary>
    public readonly string Dialog;
    /// <summary>
    /// 贴图目录
    /// </summary>
    public readonly string Texture;
    /// <summary>
    /// 3
    /// </summary>
    public readonly string Hour3;
    /// <summary>
    /// 6
    /// </summary>
    public readonly string Hour6;
    /// <summary>
    /// 9
    /// </summary>
    public readonly string Hour9;
    /// <summary>
    /// 12
    /// </summary>
    public readonly string Hour12;
    /// <summary>
    /// 15
    /// </summary>
    public readonly string Hour15;
    /// <summary>
    /// 18
    /// </summary>
    public readonly string Hour18;
    /// <summary>
    /// 21
    /// </summary>
    public readonly string Hour21;
    /// <summary>
    /// 0
    /// </summary>
    public readonly string Hour0;
   
    public const int __ID__ = -2024148906;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "power:" + Power + ","
        + "influence:" + Influence + ","
        + "interest:" + Interest + ","
        + "grouptag:" + Grouptag + ","
        + "dialog:" + Dialog + ","
        + "texture:" + Texture + ","
        + "hour3:" + Hour3 + ","
        + "hour6:" + Hour6 + ","
        + "hour9:" + Hour9 + ","
        + "hour12:" + Hour12 + ","
        + "hour15:" + Hour15 + ","
        + "hour18:" + Hour18 + ","
        + "hour21:" + Hour21 + ","
        + "hour0:" + Hour0 + ","
        + "}";
    }
}

}

