
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.story
{
public partial class Tbdialog_branch_map
{
    private readonly System.Collections.Generic.Dictionary<string, story.dialog_branch_map> _dataMap;
    private readonly System.Collections.Generic.List<story.dialog_branch_map> _dataList;
    
    public Tbdialog_branch_map(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, story.dialog_branch_map>();
        _dataList = new System.Collections.Generic.List<story.dialog_branch_map>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            story.dialog_branch_map _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = story.dialog_branch_map.Deserializedialog_branch_map(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.BranchName, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, story.dialog_branch_map> DataMap => _dataMap;
    public System.Collections.Generic.List<story.dialog_branch_map> DataList => _dataList;

    public story.dialog_branch_map GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public story.dialog_branch_map Get(string key) => _dataMap[key];
    public story.dialog_branch_map this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

