
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.story
{
public partial class Tbnpc_basic_info
{
    private readonly System.Collections.Generic.Dictionary<int, story.npc_basic_info> _dataMap;
    private readonly System.Collections.Generic.List<story.npc_basic_info> _dataList;
    
    public Tbnpc_basic_info(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, story.npc_basic_info>();
        _dataList = new System.Collections.Generic.List<story.npc_basic_info>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            story.npc_basic_info _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = story.npc_basic_info.Deserializenpc_basic_info(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, story.npc_basic_info> DataMap => _dataMap;
    public System.Collections.Generic.List<story.npc_basic_info> DataList => _dataList;

    public story.npc_basic_info GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public story.npc_basic_info Get(int key) => _dataMap[key];
    public story.npc_basic_info this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

