
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public intelligence.Tbclue_map TbclueMap {get; }
    public intelligence.Tbintelligence_map TbintelligenceMap {get; }
    public map.Tbtravel_map TbtravelMap {get; }
    public story.Tbdialog Tbdialog {get; }
    public story.Tbdialog_branch_map TbdialogBranchMap {get; }
    public story.Tbdialog_chapter_map TbdialogChapterMap {get; }
    public story.Tbdialog_illustration_map TbdialogIllustrationMap {get; }
    public story.Tbnpc_basic_info TbnpcBasicInfo {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbclueMap = new intelligence.Tbclue_map(loader("intelligence_tbclue_map"));
        TbintelligenceMap = new intelligence.Tbintelligence_map(loader("intelligence_tbintelligence_map"));
        TbtravelMap = new map.Tbtravel_map(loader("map_tbtravel_map"));
        Tbdialog = new story.Tbdialog(loader("story_tbdialog"));
        TbdialogBranchMap = new story.Tbdialog_branch_map(loader("story_tbdialog_branch_map"));
        TbdialogChapterMap = new story.Tbdialog_chapter_map(loader("story_tbdialog_chapter_map"));
        TbdialogIllustrationMap = new story.Tbdialog_illustration_map(loader("story_tbdialog_illustration_map"));
        TbnpcBasicInfo = new story.Tbnpc_basic_info(loader("story_tbnpc_basic_info"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbclueMap.ResolveRef(this);
        TbintelligenceMap.ResolveRef(this);
        TbtravelMap.ResolveRef(this);
        Tbdialog.ResolveRef(this);
        TbdialogBranchMap.ResolveRef(this);
        TbdialogChapterMap.ResolveRef(this);
        TbdialogIllustrationMap.ResolveRef(this);
        TbnpcBasicInfo.ResolveRef(this);
    }
}

}
