
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.intelligence
{
public sealed partial class clue_map : Luban.BeanBase
{
    public clue_map(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["imagePath"].IsString) { throw new SerializationException(); }  ImagePath = _buf["imagePath"]; }
    }

    public static clue_map Deserializeclue_map(JSONNode _buf)
    {
        return new intelligence.clue_map(_buf);
    }

    /// <summary>
    /// 线索id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 线索名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 图像地址
    /// </summary>
    public readonly string ImagePath;
   
    public const int __ID__ = -1446179035;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "imagePath:" + ImagePath + ","
        + "}";
    }
}

}

