
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.intelligence
{
public sealed partial class intelligence_map : Luban.BeanBase
{
    public intelligence_map(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["tag"].IsString) { throw new SerializationException(); }  Tag = _buf["tag"]; }
        { if(!_buf["descStart"].IsString) { throw new SerializationException(); }  DescStart = _buf["descStart"]; }
        { if(!_buf["descEnd"].IsString) { throw new SerializationException(); }  DescEnd = _buf["descEnd"]; }
        { if(!_buf["next"].IsString) { throw new SerializationException(); }  Next = _buf["next"]; }
        { if(!_buf["clues"].IsString) { throw new SerializationException(); }  Clues = _buf["clues"]; }
        { if(!_buf["imagePath"].IsString) { throw new SerializationException(); }  ImagePath = _buf["imagePath"]; }
    }

    public static intelligence_map Deserializeintelligence_map(JSONNode _buf)
    {
        return new intelligence.intelligence_map(_buf);
    }

    /// <summary>
    /// 情报id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 情报名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// tag
    /// </summary>
    public readonly string Tag;
    /// <summary>
    /// 开启描述
    /// </summary>
    public readonly string DescStart;
    /// <summary>
    /// 完成描述
    /// </summary>
    public readonly string DescEnd;
    /// <summary>
    /// 下一阶段
    /// </summary>
    public readonly string Next;
    /// <summary>
    /// 需要线索
    /// </summary>
    public readonly string Clues;
    /// <summary>
    /// 图像地址
    /// </summary>
    public readonly string ImagePath;
   
    public const int __ID__ = -1192577237;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "tag:" + Tag + ","
        + "descStart:" + DescStart + ","
        + "descEnd:" + DescEnd + ","
        + "next:" + Next + ","
        + "clues:" + Clues + ","
        + "imagePath:" + ImagePath + ","
        + "}";
    }
}

}

