
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.intelligence
{
public partial class Tbclue_map
{
    private readonly System.Collections.Generic.Dictionary<int, intelligence.clue_map> _dataMap;
    private readonly System.Collections.Generic.List<intelligence.clue_map> _dataList;
    
    public Tbclue_map(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, intelligence.clue_map>();
        _dataList = new System.Collections.Generic.List<intelligence.clue_map>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            intelligence.clue_map _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = intelligence.clue_map.Deserializeclue_map(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, intelligence.clue_map> DataMap => _dataMap;
    public System.Collections.Generic.List<intelligence.clue_map> DataList => _dataList;

    public intelligence.clue_map GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public intelligence.clue_map Get(int key) => _dataMap[key];
    public intelligence.clue_map this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

