
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.map
{
public partial class Tbtravel_map
{
    private readonly System.Collections.Generic.Dictionary<string, map.travel_map> _dataMap;
    private readonly System.Collections.Generic.List<map.travel_map> _dataList;
    
    public Tbtravel_map(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, map.travel_map>();
        _dataList = new System.Collections.Generic.List<map.travel_map>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            map.travel_map _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = map.travel_map.Deserializetravel_map(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, map.travel_map> DataMap => _dataMap;
    public System.Collections.Generic.List<map.travel_map> DataList => _dataList;

    public map.travel_map GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public map.travel_map Get(string key) => _dataMap[key];
    public map.travel_map this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

