
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.map
{
public sealed partial class travel_map : Luban.BeanBase
{
    public travel_map(JSONNode _buf) 
    {
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["Garden"].IsNumber) { throw new SerializationException(); }  Garden = _buf["Garden"]; }
        { if(!_buf["ThePalace"].IsNumber) { throw new SerializationException(); }  ThePalace = _buf["ThePalace"]; }
        { if(!_buf["Library"].IsNumber) { throw new SerializationException(); }  Library = _buf["Library"]; }
    }

    public static travel_map Deserializetravel_map(JSONNode _buf)
    {
        return new map.travel_map(_buf);
    }

    /// <summary>
    /// 地点名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Garden
    /// </summary>
    public readonly int Garden;
    /// <summary>
    /// The Palace
    /// </summary>
    public readonly int ThePalace;
    /// <summary>
    /// Library
    /// </summary>
    public readonly int Library;
   
    public const int __ID__ = -762380663;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "Garden:" + Garden + ","
        + "ThePalace:" + ThePalace + ","
        + "Library:" + Library + ","
        + "}";
    }
}

}

